package:
  name: boost
  version: 1.54.0 

source:
  fn: boost_1_54_0.tar.gz
  url: http://downloads.sourceforge.net/project/boost/boost/1.54.0/boost_1_54_0.tar.gz?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Fboost%2Ffiles%2Fboost%2F1.54.0%2F&ts=1384024111&use_mirror=softlayer-dal
  sha1: 069501636097d3f40ddfd996d29748bb23591c53

about:
  home: http://www.boost.org
  license: Boost 1.0
